version: "3.8"

x-env: &x-env
  APP_URL: ${APP_URL:-}
  KEY_VAULTS_SECRET: ${KEY_VAULTS_SECRET:-}
  DATABASE_URL: postgres://lobechat:${POSTGRES_PASSWORD}@postgres:5432/lobechat
  NEXT_AUTH_SECRET: ${NEXT_AUTH_SECRET:-}
  NEXT_AUTH_SSO_PROVIDERS: ${NEXT_AUTH_SSO_PROVIDERS:-}
  NEXTAUTH_URL: ${NEXTAUTH_URL:-}
  AUTH_AUTH0_ID: ${AUTH_AUTH0_ID:-}
  AUTH_AUTH0_SECRET: ${AUTH_AUTH0_SECRET:-}
  AUTH_AUTH0_ISSUER: ${AUTH_AUTH0_ISSUER:-}
  S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-}
  S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-}
  S3_ENDPOINT: ${S3_ENDPOINT:-}
  S3_BUCKET: ${S3_BUCKET:-}
  S3_PUBLIC_DOMAIN: ${S3_PUBLIC_DOMAIN:-}
  S3_REGION: ${S3_REGION:-}

services:
  lobe-chat:
    image: lobehub/lobe-chat-database
    restart: always
    environment:
      <<: *x-env
    networks:
      - dokply-network
    expose:
      - 3210
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.<UNIQUE-RULE>.rule=Host('domain.name.tld')
      - traefik.http.services.<UNIQUE-RULE>.loadbalancer.server.port=3210
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: lobechat
      POSTGRES_USER: lobechat
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rGKiCy1K33n8Qb}
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - dokply-network

volumes:
  db-data:
